### ISSUE TITLE
StarNet won't execute on Mac

### ISSUE THREAD

**Issue by FrancescoDT05** [Ripwords/starnetGUI#3]
Hi! I'm trying to run StarNet on my M31 astrophoto. I tried running the command line version of StarNet from the Terminal but it said Permission Denied no matter what I tried to do.
So I stumbled upon this GUI version for Mac. I installed it, set the directory properly, added the image to process, output directory and everything. I then clicked on StarNet and the progress bar went super fast for a few seconds, then it stopped and after the 10000 ms timeout delay it gave two messages saying "StarNet Timed Out" and "Check StarNet Directory". There, the temporary file got deleted and nothing else happened.

Full list of messages:
Running StarNet...
StarNet Timed Out.
Check StarNet Directory.

How can I fix this?

**Comment by Ripwords** [comment]
Okay so, the GUI is just an interface, you should still make sure you're able to run the CLI version first. I had another user who reported the exact same issue to me yesterday. The issue is macOS does not allow third party applications to run without providing explicit permission, without being able to run the CLI, you won't be able to run the GUI as well.

The timeout is caused by the same error as the CLI, because behind the scenes, the GUI is just calling the CLI version. The reason for the timeout is to identify issues like this.

[https://www.youtube....h?v=km4wKo8P50s](https://www.youtube.com/watch?v=km4wKo8P50s)
( you can start from the beginning or skip to 4:45 )

Here's a video on setting up the CLI on MacOS, once you have the CLI working, the GUI should be able to work once you point it to the correct directory. There are also forums on CloudyNights about people teaching people how to run starnet properly on macOS. You can refer to [this](https://www.cloudynights.com/topic/808556-starnet-v2/page-3#entry11671654) from the forum.

Let me know if you need further assistance :)

**Comment by FrancescoDT05** [comment]
Thank you for the quick response!
Okay so I was just giving chmod +x to the script I wanted to execute, not to all of them. That was the issue. Thanks again!!

**Comment by Ripwords** [comment]
You're welcome!
