### ISSUE TITLE
starnet-gui_1.1.1_amd64.AppImage doesn't start

### ISSUE THREAD

**Issue by loop974** [Ripwords/starnetGUI#6]
Hello again,
I sent you the message on YT.
I did what you told me ( “Allow executing file as program”) and nothing happens.
For information, i am using Siril in the AppImage version, and it works properly.
Any idea why it doesn't work ?
My OS is Kubuntu 18.04.
Thanks.

**Comment by Ripwords** [comment]
As I don't have a Linux machine as of now you may need to give me a bit of time to install it and try it myself. I'll get back to you soon

**Comment by Ripwords** [comment]
I have not been able to find an installation media of Kubuntu 18.04 as it is no longer supported and available. There are a few things I'd like to try, i have tried again on Linux and it is working still, so the first thing i want to make sure is that if you have FUSE installed? Using terminal type:
`sudo apt install fuse`

However since you have Siril's AppImage installed you should already have FUSE installed. The second thing i'd like to try is to run the the gui AppImage using the terminal by:
1. Going to the installation folder
2. Right-click and click "Open in Terminal"
3. type ./starnet-gui_1.1.1_amd64.AppImage
4. Let me know if the app runs, or let me know any error messages comes out

**Comment by loop974** [comment]
Hello,
I did what you asked me.
Fuse is already installed, and it seems that libOpenGL.so.0 is missing.
I suppose that i should install it.
Just confirm me.
Thanks.

![Konsole_20230302](https://user-images.githubusercontent.com/126725626/222351317-ca044ceb-c011-4735-8695-4dd678516f1c.png)

**Comment by Ripwords** [comment]
This to me seems like Kubuntu 18.04 does not have OpenGL installed. A quick google search showed two solutions from [this](https://stackoverflow.com/questions/65751536/importerror-libopengl-so-0-cannot-open-shared-object-file-no-such-file-or-dir) link. I am not sure if the simpler solution would work for you, if it does then that's great if not you may need to try the second solution.

1. `sudo apt install libopengl0 -y`
2. `sudo apt-get install freeglut3 freeglut3-dev`

**Comment by loop974** [comment]
Ok, so both solutions have no effect.
I will check if upgrading my kubuntu to latest stable version may offer a solution.
I'll keep you advise in the next days if my problem is solved or not.
Again, thanks for your help.

**Comment by Ripwords** [comment]
I'm sorry I'm unable to fix your issue as it's not directly related with my application, and I am not as familiar with the linux OS. Do update me and I will try to solve the issue

**Comment by loop974** [comment]
helleo,
I have just upgraded my OS to version 22.04, then i launch Starnet, and then :
![SStarnet_20230302](https://user-images.githubusercontent.com/126725626/222499463-e4f97805-fccb-4a64-9ed7-d8ee0a5091d3.png)

It seems that it works !
Now I'm gonna learn how to use it !
Thanks !

**Comment by Ripwords** [comment]
I'm glad that the issue is resolved, i will make an updated tutorial when i have more time. The youtube video i made awhile ago is pretty messy but it should be enough to get you going on learning it
